steps:
  # 0. Run Backend Tests
  - name: 'python:3.10-slim'
    id: 'run-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r backend/requirements.txt
        export DATABASE_URL="sqlite+aiosqlite:///./test.db"
        export SECRET_KEY="test-secret-key"
        export OPENAI_API_KEY="sk-dummy"
        export GEMINI_API_KEY="dummy"
        export PYTHONPATH=.
        cd backend && pytest

  # 1. Security Scanning (Backend)
  - name: 'python:3.10-slim'
    id: 'backend-security-scan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install bandit pip-audit
        # Run bandit for SAST (ignoring B104 for binding to all interfaces in container)
        bandit -r backend/app -s B104
        # Run pip-audit for dependencies (ignoring unfixable ecdsa vuln)
        pip-audit -r backend/requirements.txt --ignore-vuln CVE-2024-23342

  # 2. Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    waitFor: ['run-tests']
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/boutique-backend', './backend']
  
  # 2. Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args: ['push', 'gcr.io/$PROJECT_ID/boutique-backend']

  # 3. Security Scanning (Frontend)
  - name: 'node:18'
    id: 'frontend-security-scan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        # Fail if there are high/critical vulnerabilities
        npm audit --audit-level=high

  # 3. Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/boutique-frontend', '--build-arg', 'VITE_API_URL=${_BACKEND_URL}', './frontend']

  # 4. Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args: ['push', 'gcr.io/$PROJECT_ID/boutique-frontend']

  # 5. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'boutique-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/boutique-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_INSTANCE_CONNECTION_NAME}'
      - '--update-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},SECRET_KEY=${_SECRET_KEY},OPENAI_API_KEY=${_OPENAI_API_KEY},GEMINI_API_KEY=${_GEMINI_API_KEY},OPENAI_MODEL=${_OPENAI_MODEL},GEMINI_MODEL=${_GEMINI_MODEL},SMTP_HOST=${_SMTP_HOST},SMTP_PORT=${_SMTP_PORT},SMTP_USER=${_SMTP_USER},SMTP_PASSWORD=${_SMTP_PASSWORD},SMTP_FROM_EMAIL=${_SMTP_FROM_EMAIL},FIRST_SUPERUSER=${_FIRST_SUPERUSER},FIRST_SUPERUSER_PASSWORD=${_FIRST_SUPERUSER_PASSWORD}'

  # 6. Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'boutique-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/boutique-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _DATABASE_URL: ''
  _SECRET_KEY: ''
  _INSTANCE_CONNECTION_NAME: ''
  _BACKEND_URL: ''
  _OPENAI_API_KEY: ''
  _GEMINI_API_KEY: ''
  _OPENAI_MODEL: 'gpt-4o-mini'
  _GEMINI_MODEL: 'gemini-1.5-pro'
  _SMTP_HOST: 'smtp.gmail.com'
  _SMTP_PORT: '587'
  _SMTP_USER: ''
  _SMTP_PASSWORD: ''
  _SMTP_FROM_EMAIL: ''
  _FIRST_SUPERUSER: ''
  _FIRST_SUPERUSER_PASSWORD: ''

images:
  - 'gcr.io/$PROJECT_ID/boutique-backend'
  - 'gcr.io/$PROJECT_ID/boutique-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
