"""Add company_name and designation to User

Revision ID: f17fbdcb6a05
Revises: 1000000000000
Create Date: 2026-02-16 05:51:04.592683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17fbdcb6a05'
down_revision: Union[str, Sequence[str], None] = '1000000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('designation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'designation')
    op.drop_column('user', 'company_name')
    # ### end Alembic commands ###
